### ISSUE TITLE
Python 3.8 compatibility issue - Multiple Exception - ValueError: Invalid format specifier

### ISSUE THREAD

**Issue by digitalsleuth** [TeamMsgExtractor/msg-extractor#169]
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* Version of extract_msg: [x.x.x] `0.27.9 - installed with pip3 install git+https://github.com/TeamMsgExtractor/msg-extractor`
* Your python version: Python [2.7 | 3.6.7] `3.8.5 - Ubuntu 20.04 LTS default python version`
* How did you launch extract_msg?
  - [ ] My command line or
  - [ ] I used the extract_msg package
  - [*] All of the above `Errors with both the extract_msg cmd line and python3 import method`
**Describe the bug**

When running this tool in Ubuntu 18.04 LTS with a default python version of 3.6.9 there are no issues extracting the content. Utilizing the same method (either `extract_msg Test.msg` or `import extract_msg; msg = extract_msg.openMsg("Test.msg")`), the file does not open, and provides several errors (During handling of the above exception, another exception occurred):

**What code did you use or can we use to reproduce this error?

```
extract_msg Test.msg

or 

import extract_msg
msg = extract_msg.openMsg("Test.msg")

```

Is there a message.msg file you want to share to help us reproduce this?
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]
- Unable to provide at this time, error can be duplicated with multiple msg files (all tested have attachments)

**Traceback**
```
>>> import extract_msg
>>> msg = extract_msg.openMsg("Test.msg")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/extract_msg/message_base.py", line 243, in header
    return self._header
AttributeError: 'Message' object has no attribute '_header'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/extract_msg/message_base.py", line 232, in date
    return self._date
AttributeError: 'Message' object has no attribute '_date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/extract_msg/properties.py", line 128, in date
    return self.__date
AttributeError: 'Properties' object has no attribute '_Properties__date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/extract_msg/utils.py", line 366, in openMsg
    return Message(path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding)
  File "/usr/local/lib/python3.8/dist-packages/extract_msg/message.py", line 28, in __init__
    MessageBase.__init__(self, path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding)
  File "/usr/local/lib/python3.8/dist-packages/extract_msg/message_base.py", line 51, in __init__
    self.header
  File "/usr/local/lib/python3.8/dist-packages/extract_msg/message_base.py", line 248, in header
    self._header['date'] = self.date
  File "/usr/local/lib/python3.8/dist-packages/extract_msg/message_base.py", line 234, in date
    self._date = self._prop.date
  File "/usr/local/lib/python3.8/dist-packages/extract_msg/properties.py", line 131, in date
    self.__date = self.get('00390040').value.__format__('%a, %d %b %Y %H:%M:%S %z')
ValueError: Invalid format specifier
```

**Screenshots**
NIL

**Additional context**
Exact same msg files work perfectly in python 3.6.9. Both python versions are installed in the absolute bare-minimum versions of their respective Ubuntu LTS (3.6.9 in 18.04 and 3.8.5 in Ubuntu 20.04)

**Comment by TheElementalOfDestruction** [comment]
The error you put is not correct. The correct error would be "ValueError: Invalid format specifier". Please change your title. 

The error seems to be with the datetime object when it is being formatted, but I don't know why. It is possible they decided to change one of the format specifiers which might be a pain to fix.

I'll look into it and see if I can replicate the issue.

**Comment by TheElementalOfDestruction** [comment]
I was unable to replicate this issue (I tried it on Ubuntu with the same version of python). Below is an image of my running the tests to show that I do not get an error.

![image](https://user-images.githubusercontent.com/24580325/102170108-78315b00-3e48-11eb-9daa-403525deb5cf.png)

Would it be possible for you to try running this code on your 3.8.5 version of Python and see if it has the same error?
```python
import datetime
print(datetime.datetime.now().__format__('%a, %d %b %Y %H:%M:%S %z'))
```

**Comment by digitalsleuth** [comment]
Found the issue. Tried running the commands you gave me and got the error:
```
print(datetime.datetime.now(tzlocal.get_localzone()).__format__('%a, %d %b %Y %H:%M:%S zZ'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.8/dist-packages/tzlocal/unix.py", line 86, in _get_localzone
    tz = pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/lib/python3/dist-packages/pytz/__init__.py", line 181, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: '/UTC'
```
Turns out the barebones Ubuntu 20.04 does not come with the tzdata package.
Installed tzdata using `apt install tzdata` and the tool now works. This also occurs in a docker environment as well, for anyone finding this thread and getting the same error within a container.

Thanks!

**Comment by CribberSix** [comment]
I am running Python 3.8.3 on Win10 and I encountered the same problem. Weirdly, the script itself works, but once I package it with pyinstaller as an executable, I get the `ValueError: Invalid format specifier` error. I included `tzdata` in the imports for the executable but the problem persists. 


```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "extract_msg\message_base.py", line 261, in header
AttributeError: 'Message' object has no attribute '_header'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "extract_msg\message_base.py", line 250, in date
AttributeError: 'Message' object has no attribute '_date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "extract_msg\properties.py", line 128, in date
AttributeError: 'Properties' object has no attribute '_Properties__date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "tkinter_application.py", line 151, in parse_all_mails
  File "mail_parser.py", line 51, in parse_and_write_into_xlsm
  File "mail_parser.py", line 93, in parse_mail
  File "extract_msg\message.py", line 29, in __init__
  File "extract_msg\message_base.py", line 53, in __init__
  File "extract_msg\message_base.py", line 266, in header
  File "extract_msg\message_base.py", line 252, in date
  File "extract_msg\properties.py", line 131, in date
ValueError: Invalid format specifier
```

**Comment by CribberSix** [comment]
Same error is happening on python 3.6.0 after packaging weirdly...

**Comment by CribberSix** [comment]
After downgrading to `extract-msg==0.27.4` it works again... seems that it was some newer change that caused the problem for me.

**Comment by TheElementalOfDestruction** [comment]
So you are saying that the newest version that works in 0.27.4 and not 0.27.5? I have to ask that you are sure that is the newest version because between those 2 there were _no changes_ to the datetime code, as far as I can tell. With python 3.6 I also receive no data time issues about invalid specifier so I'm not sure exactly why you are getting it.

**Comment by CribberSix** [comment]
I specifically mentioned: "So it **doesn't** have to be the next update after 0.27.4 that caused the problem." 
I don't know which version caused the change, I just picked an older one (0.27.4) and it worked. 

I just checked and there seems to be a packaging problem with tzlocal - I had to manually add tzdata & tzlocal to the package, but once packaged it trys look up a file  in a directory that doesn't exist on windows.  I will create an issue on their repo. 

For now - is the dependency on tzlocal a newer one for the msg-extract package?

**Comment by TheElementalOfDestruction** [comment]
No, the dependency was added a while back when the need for displaying the dates in the current time (instead of just the time in UTC) became important. If you can come up with a reasonable alternative that works reliably I am open to suggestions, but for now I really need it.

**Comment by CribberSix** [comment]
Fair point! I am fine to work with an old version of the package tbh. I just thought I'd at least try and identify the issue :)  Thanks and have a great weekend!
